spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: test2755
  jpa:
    hibernate:
      ddl-auto: update
resilience4j:
  circuitbreaker:
    instances:
      customers:
        register-health-indicator: true
        automaticTransitionFromOpenToHalfOpenEnabled: true
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        wait-duration-in-open-state: 10s
        failure-rate-threshold: 50
        eventConsumerBufferSize: 10

